# Redis Secret
# base64 encoded: echo -n 'redispassword123' | base64 => cmVkaXNwYXNzd29yZDEyMw==

apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: microshop
type: Opaque
data:
  password: cmVkaXNwYXNzd29yZDEyMw==  # redispassword123
