apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microshop-dev

bases:
  - ../../base

namePrefix: dev-

replicas:
  - name: frontend-service
    count: 1
  - name: product-service
    count: 1
  - name: order-service
    count: 1
  - name: mongodb
    count: 1

configMapGenerator:
  - name: product-service-config
    behavior: merge
    literals:
      - log_level=debug
