apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microshop-staging

bases:
  - ../../base

namePrefix: staging-

replicas:
  - name: frontend-service
    count: 2
  - name: product-service
    count: 2
  - name: order-service
    count: 2
  - name: mongodb
    count: 3

configMapGenerator:
  - name: product-service-config
    behavior: merge
    literals:
      - log_level=info
